### ISSUE TITLE
 java.lang.RuntimeException: Unable to start activity

### ISSUE THREAD

**Issue by asad1492** [MAXDeliveryNG/slideview#5] opened 2017-09-27 14:17 UTC
I am facing this exception while adding a slide view in my activity. 

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.infogistic.cloudclinik/com.example.saeeda.cloudclinik.activity.CallingActivity}: android.view.InflateException: Binary XML file line #122: Binary XML file line #122: Error inflating class ng.max.slideview.SlideView`

**Comment by kizitonwose** [comment] 2017-09-27 14:44
Can you please provide a sample project with this issue?

**Comment by kizitonwose** [comment] 2017-11-03 16:56
Closing this issue since error can't be reproduced.

**Closed** 2017-11-03 16:57 UTC
